In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Sample.csv", encoding="cp1252")

In [3]:
df.head(10)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
5,6,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.8600,7,0.00,14.1694
6,7,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.2800,4,0.00,1.9656
7,8,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,TEC-PH-10002275,Technology,Phones,Mitel 5320 IP Phone VoIP phone,907.1520,6,0.20,90.7152
8,9,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-BI-10003910,Office Supplies,Binders,DXL Angle-View Binders with Locking Rings by S...,18.5040,3,0.20,5.7825
9,10,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-AP-10002892,Office Supplies,Appliances,Belkin F5C206VTEL 6 Outlet Surge,114.9000,5,0.00,34.4700

In [4]:
df.tail(5)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
9989,9990,CA-2014-110422,1/21/2014,1/23/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.248,3,0.2,4.1028
9990,9991,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.960,2,0.0,15.6332
9991,9992,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.576,2,0.2,19.3932
9992,9993,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.600,4,0.0,13.3200
9993,9994,CA-2017-119914,5/4/2017,5/9/2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.160,2,0.0,72.9480

#### Task 4. Find the total number of rows and columns.

In [5]:
df.shape

(9994, 21)

#### Task 5. Display the column names, data types, and non-null counts.

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB

### Use your existing DataFrame: df

#### Task 1: Check the number of missing values in each column.

In [7]:
df.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

#### Task 2: Check whether any duplicate rows exist.

df.duplicated()

#### Task 3: Remove duplicate rows from the dataset.

In [8]:
df.drop_duplicates()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,1/21/2014,1/23/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,9991,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,9992,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,9993,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,9994,CA-2017-119914,5/4/2017,5/9/2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

#### Task 4: Convert the Order Date and Ship Date columns to datetime format.

In [32]:
df["Order Date"] = pd.to_datetime(df["Order Date"])
df["Ship Date"] = pd.to_datetime(df["Ship Date"])

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   datetime64[ns]
 3   Ship Date      9994 non-null   datetime64[ns]
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: datetime64[ns](2), float64(3), int64(3), object(13)
memory usage: 1.6+ MB

#### Task 6: Create a new column named Ship_Days that calculates the number of days between Ship Date and Order Date.

In [10]:
df["Ship_Days"] = (df["Ship Date"] - df["Order Date"]).dt.days

In [12]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Ship_Days
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,3
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,3
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,4
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,7
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,7

### Stage 3 — Data Filtering & Sorting

### Task 1:
#### Display all orders where Sales is greater than 500.

In [13]:
df[df["Sales"] > 500]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Ship_Days
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,3
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,7
7,8,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,West,TEC-PH-10002275,Technology,Phones,Mitel 5320 IP Phone VoIP phone,907.1520,6,0.20,90.7152,5
10,11,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,West,FUR-TA-10001539,Furniture,Tables,Chromcraft Rectangular Conference Tables,1706.1840,9,0.20,85.3092,5
11,12,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,West,TEC-PH-10002033,Technology,Phones,Konftel 250 Conference phone - Charcoal black,911.4240,4,0.20,68.3568,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9931,9932,CA-2015-104948,2015-11-13,2015-11-17,Standard Class,KH-16510,Keith Herrera,Consumer,United States,San Bernardino,...,West,FUR-BO-10004357,Furniture,Bookcases,O'Sullivan Living Dimensions 3-Shelf Bookcases,683.3320,4,0.15,-40.1960,4
9942,9943,CA-2014-143371,2014-12-28,2015-01-03,Standard Class,MD-17350,Maribeth Dona,Consumer,United States,Anaheim,...,West,OFF-ST-10001128,Office Supplies,Storage,"Carina Mini System Audio Rack, Model AR050B",998.8200,9,0.00,29.9646,6
9947,9948,CA-2017-121559,2017-06-01,2017-06-03,Second Class,HW-14935,Helen Wasserman,Corporate,United States,Indianapolis,...,Central,FUR-CH-10003746,Furniture,Chairs,Hon 4070 Series Pagoda Round Back Stacking Chairs,1925.8800,6,0.00,539.2464,2
9948,9949,CA-2017-121559,2017-06-01,2017-06-03,Second Class,HW-14935,Helen Wasserman,Corporate,United States,Indianapolis,...,Central,OFF-AP-10002945,Office Supplies,Appliances,Honeywell Enviracaire Portable HEPA Air Cleane...,2405.2000,8,0.00,793.7160,2
9968,9969,CA-2017-153871,2017-12-11,2017-12-17,Standard Class,RB-19435,Richard Bierner,Consumer,United States,Plainfield,...,East,OFF-BI-10004600,Office Supplies,Binders,Ibico Ibimaster 300 Manual Binding System,735.9800,2,0.00,331.1910,6

### Task 2:
#### Display all orders where Profit is negative.

In [22]:
Loss = df[df["Profit"] < 0]
Loss.shape

(1871, 22)

### Task 4:
#### Display orders where Sales is greater than 500 AND Profit is greater than 100.

In [20]:
Total_Sales = df[(df["Sales"] > 500) & (df["Profit"] > 100)]
Total_Sales.shape

(630, 22)

### Task 5:
#### Display orders where Region is either "West" or "East".

In [24]:
Region = df[(df["Region"] =="West") | (df["Region"] == "East")]
Region.shape

(6051, 22)

### Task 6:
#### Sort the dataset by Sales in descending order.

In [25]:
sort_value = df.sort_values("Sales", ascending=False)
sort_value

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Ship_Days
2697,2698,CA-2014-145317,2014-03-18,2014-03-23,Standard Class,SM-20320,Sean Miller,Home Office,United States,Jacksonville,...,South,TEC-MA-10002412,Technology,Machines,Cisco TelePresence System EX90 Videoconferenci...,22638.480,6,0.5,-1811.0784,5
6826,6827,CA-2016-118689,2016-10-02,2016-10-09,Standard Class,TC-20980,Tamara Chand,Corporate,United States,Lafayette,...,Central,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,17499.950,5,0.0,8399.9760,7
8153,8154,CA-2017-140151,2017-03-23,2017-03-25,First Class,RB-19360,Raymond Buch,Consumer,United States,Seattle,...,West,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,13999.960,4,0.0,6719.9808,2
2623,2624,CA-2017-127180,2017-10-22,2017-10-24,First Class,TA-21385,Tom Ashbrook,Home Office,United States,New York City,...,East,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,11199.968,4,0.2,3919.9888,2
4190,4191,CA-2017-166709,2017-11-17,2017-11-22,Standard Class,HL-15040,Hunter Lopez,Consumer,United States,Newark,...,East,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,10499.970,3,0.0,5039.9856,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2106,2107,US-2014-152723,2014-09-26,2014-09-26,Same Day,HG-14965,Henry Goldwyn,Corporate,United States,Mesquite,...,Central,OFF-BI-10003460,Office Supplies,Binders,Acco 3-Hole Punch,0.876,1,0.8,-1.4016,0
4711,4712,CA-2014-112403,2014-03-31,2014-03-31,Same Day,JO-15280,Jas O'Carroll,Consumer,United States,Philadelphia,...,East,OFF-BI-10003529,Office Supplies,Binders,Avery Round Ring Poly Binders,0.852,1,0.7,-0.5964,0
8658,8659,CA-2016-168361,2016-06-21,2016-06-25,Standard Class,KB-16600,Ken Brennan,Corporate,United States,Chicago,...,Central,OFF-BI-10003727,Office Supplies,Binders,Avery Durable Slant Ring Binders With Label Ho...,0.836,1,0.8,-1.3376,4
9292,9293,CA-2017-124114,2017-03-02,2017-03-02,Same Day,RS-19765,Roland Schwarz,Corporate,United States,Waco,...,Central,OFF-BI-10004022,Office Supplies,Binders,Acco Suede Grain Vinyl Round Ring Binder,0.556,1,0.8,-0.9452,0
4101,4102,US-2017-102288,2017-06-19,2017-06-23,Standard Class,ZC-21910,Zuschuss Carroll,Consumer,United States,Houston,...,Central,OFF-AP-10002906,Office Supplies,Appliances,Hoover Replacement Belt for Commercial Guardsm...,0.444,1,0.8,-1.1100,4

### Task 7:
#### Display the top 10 orders with the highest Profit.

In [50]:
Top_10 = df.sort_values("Profit", ascending=False)
Top_10.head(10)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Ship_Days
6826,6827,CA-2016-118689,2016-10-02,2016-10-09,Standard Class,TC-20980,Tamara Chand,Corporate,United States,Lafayette,...,Central,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,17499.950,5,0.0,8399.9760,7
8153,8154,CA-2017-140151,2017-03-23,2017-03-25,First Class,RB-19360,Raymond Buch,Consumer,United States,Seattle,...,West,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,13999.960,4,0.0,6719.9808,2
4190,4191,CA-2017-166709,2017-11-17,2017-11-22,Standard Class,HL-15040,Hunter Lopez,Consumer,United States,Newark,...,East,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,10499.970,3,0.0,5039.9856,5
9039,9040,CA-2016-117121,2016-12-17,2016-12-21,Standard Class,AB-10105,Adrian Barton,Consumer,United States,Detroit,...,Central,OFF-BI-10000545,Office Supplies,Binders,GBC Ibimaster 500 Manual ProClick Binding System,9892.740,13,0.0,4946.3700,4
4098,4099,CA-2014-116904,2014-09-23,2014-09-28,Standard Class,SC-20095,Sanjit Chand,Consumer,United States,Minneapolis,...,Central,OFF-BI-10001120,Office Supplies,Binders,Ibico EPK-21 Electric Binding System,9449.950,5,0.0,4630.4755,5
2623,2624,CA-2017-127180,2017-10-22,2017-10-24,First Class,TA-21385,Tom Ashbrook,Home Office,United States,New York City,...,East,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,11199.968,4,0.2,3919.9888,2
509,510,CA-2015-145352,2015-03-16,2015-03-22,Standard Class,CM-12385,Christopher Martinez,Consumer,United States,Atlanta,...,South,OFF-BI-10003527,Office Supplies,Binders,Fellowes PB500 Electric Punch Plastic Comb Bin...,6354.950,5,0.0,3177.4750,6
8488,8489,CA-2016-158841,2016-02-02,2016-02-04,Second Class,SE-20110,Sanjit Engle,Consumer,United States,Arlington,...,South,TEC-MA-10001127,Technology,Machines,HP Designjet T520 Inkjet Large Format Printer ...,8749.950,5,0.0,2799.9840,2
7666,7667,US-2016-140158,2016-10-04,2016-10-08,Standard Class,DR-12940,Daniel Raglin,Home Office,United States,Providence,...,East,TEC-CO-10001449,Technology,Copiers,Hewlett Packard LaserJet 3310 Copier,5399.910,9,0.0,2591.9568,4
6520,6521,CA-2017-138289,2017-01-16,2017-01-18,Second Class,AR-10540,Andy Reiter,Consumer,United States,Jackson,...,Central,OFF-BI-10004995,Office Supplies,Binders,GBC DocuBind P400 Electric Binding System,5443.960,4,0.0,2504.2216,2

### Task 8:
#### Display all orders where Discount is greater than or equal to 0.3,
#### and show only these columns:
#### Order ID, Product Name, Sales, Discount, Profit.

In [32]:
display_discount = df[df["Discount"] >= 0.3]
display_discount = display_discount[["Order ID", "Product Name", "Sales", "Discount","Profit"]]
display_discount

,Order ID,Product Name,Sales,Discount,Profit
3,US-2015-108966,Bretford CR4500 Series Slim Rectangular Table,957.5775,0.45,-383.0310
14,US-2015-118983,Holmes Replacement Filter for HEPA Air Cleaner...,68.8100,0.80,-123.8580
15,US-2015-118983,Storex DuraTech Recycled Plastic Frosted Binders,2.5440,0.80,-3.8160
23,US-2017-156909,"Global Deluxe Stacking Chair, Gray",71.3720,0.30,-1.0196
27,US-2015-150630,"Riverside Palais Royal Lawyers Bookcase, Royal...",3083.4300,0.50,-1665.0522
...,...,...,...,...,...
9903,CA-2014-122609,"GE General Use Halogen Bulbs, 100 Watts, 1 Bul...",25.1280,0.60,-6.9102
9919,CA-2016-149272,Novimex Swivel Fabric Task Chair,528.4300,0.30,-143.4310
9920,CA-2016-149272,"GBC Pre-Punched Binding Paper, Plastic, White,...",22.3860,0.80,-35.8176
9921,CA-2014-111360,Acco Expandable Hanging Binders,5.7420,0.70,-4.5936
9962,CA-2015-168088,Bush Heritage Pine Collection 5-Shelf Bookcase...,383.4656,0.32,-67.6704

## GroupBy & Aggregation

### Task 1:
#### Calculate total Sales for each Category.

In [37]:
sale_cateogry_vale = df.groupby("Category")["Sales"].sum()
sale_cateogry_vale

Category
Furniture          741999.7953
Office Supplies    719047.0320
Technology         836154.0330
Name: Sales, dtype: float64

### Task 2:
#### Calculate total Profit for each Category.

In [38]:
tf = df.groupby("Category")["Profit"].sum()
tf

Category
Furniture           18451.2728
Office Supplies    122490.8008
Technology         145454.9481
Name: Profit, dtype: float64

### Task 3:
#### Calculate total Sales for each Region.

In [39]:
ts = df.groupby("Region")["Sales"].sum()
ts

Region
Central    501239.8908
East       678781.2400
South      391721.9050
West       725457.8245
Name: Sales, dtype: float64

### Task 4:
#### Calculate average Sales for each Segment.

In [40]:
As = df.groupby("Segment")["Sales"].mean()
As

Segment
Consumer       223.733644
Corporate      233.823300
Home Office    240.972041
Name: Sales, dtype: float64

### Task 5:
#### Find the total Quantity sold for each Sub-Category.

In [42]:
tq = df.groupby("Sub-Category")["Quantity"].sum()
tq

Sub-Category
Accessories    2976
Appliances     1729
Art            3000
Binders        5974
Bookcases       868
Chairs         2356
Copiers         234
Envelopes       906
Fasteners       914
Furnishings    3563
Labels         1400
Machines        440
Paper          5178
Phones         3289
Storage        3158
Supplies        647
Tables         1241
Name: Quantity, dtype: int64

### Task 6:
#### Calculate total Sales and total Profit for each Region in a single result.

In [43]:
t = df.groupby("Region")[["Sales", "Profit"]].sum()
t

               Sales       Profit
Region
Central  501239.8908   39706.3625
East     678781.2400   91522.7800
South    391721.9050   46749.4303
West     725457.8245  108418.4489

### Task 7:
#### Find the top 5 States with the highest total Sales.

In [55]:
hts = df.groupby("State")["Sales"].sum()
top_5_states = hts.sort_values(ascending=False).head(5)
top_5_states

State
California      457687.6315
New York        310876.2710
Texas           170188.0458
Washington      138641.2700
Pennsylvania    116511.9140
Name: Sales, dtype: float64

### Task 8:
#### Calculate total Sales for each Category and Sub-Category.

In [47]:
cs = df.groupby(["Category","Sub-Category"])["Sales"].sum()
cs

Category         Sub-Category
Furniture        Bookcases       114879.9963
                 Chairs          328449.1030
                 Furnishings      91705.1640
                 Tables          206965.5320
Office Supplies  Appliances      107532.1610
                 Art              27118.7920
                 Binders         203412.7330
                 Envelopes        16476.4020
                 Fasteners         3024.2800
                 Labels           12486.3120
                 Paper            78479.2060
                 Storage         223843.6080
                 Supplies         46673.5380
Technology       Accessories     167380.3180
                 Copiers         149528.0300
                 Machines        189238.6310
                 Phones          330007.0540
Name: Sales, dtype: float64

### Task 9:
#### Calculate total Sales, total Profit, and average Discount
#### for each Category.

In [49]:
tds = df.groupby("Category").agg({
    "Sales": "sum",
    "Profit": "sum",
    "Discount": "mean"
})
tds

                       Sales       Profit  Discount
Category
Furniture        741999.7953   18451.2728  0.173923
Office Supplies  719047.0320  122490.8008  0.157285
Technology       836154.0330  145454.9481  0.132323

In [52]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit', 'Ship_Days'],
      dtype='object')

## Sales & Profit Analysis

### Task 1:
#### Calculate the total revenue (Sales) of the entire dataset.

In [9]:
tl = df ["Sales"].sum()
tl

np.float64(2297200.8603)

### Task 2:
#### Calculate the total Profit of the entire dataset.

In [10]:
tnf = df["Profit"].sum()
tnf

np.float64(286397.0217)

### Task 3:
#### Calculate the overall Profit Margin as a percentage.
##### Formula: (Total Profit / Total Sales) * 100

In [14]:
profit_percent_margin = (tnf/tl)* 100
profit_percent_margin

np.float64(12.467217240315605)

In [19]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

### Task 4:
#### Find the 10 products with the highest total Sales.

In [25]:
top = df.groupby("Product Name")["Sales"].sum().nlargest(10)
top

Product Name
Canon imageCLASS 2200 Advanced Copier                                          61599.824
Fellowes PB500 Electric Punch Plastic Comb Binding Machine with Manual Bind    27453.384
Cisco TelePresence System EX90 Videoconferencing Unit                          22638.480
HON 5400 Series Task Chairs for Big and Tall                                   21870.576
GBC DocuBind TL300 Electric Binding System                                     19823.479
GBC Ibimaster 500 Manual ProClick Binding System                               19024.500
Hewlett Packard LaserJet 3310 Copier                                           18839.686
HP Designjet T520 Inkjet Large Format Printer - 24" Color                      18374.895
GBC DocuBind P400 Electric Binding System                                      17965.068
High Speed Automatic Electric Letter Opener                                    17030.312
Name: Sales, dtype: float64

### Task 5:
#### Find the 10 products with the lowest total Profit.

In [29]:
low = df.groupby("Product Name")["Profit"].sum().nsmallest(10)
low

Product Name
Cubify CubeX 3D Printer Double Head Print                           -8879.9704
Lexmark MX611dhe Monochrome Laser Printer                           -4589.9730
Cubify CubeX 3D Printer Triple Head Print                           -3839.9904
Chromcraft Bull-Nose Wood Oval Conference Tables & Bases            -2876.1156
Bush Advantage Collection Racetrack Conference Table                -1934.3976
GBC DocuBind P400 Electric Binding System                           -1878.1662
Cisco TelePresence System EX90 Videoconferencing Unit               -1811.0784
Martin Yale Chadless Opener Electric Letter Opener                  -1299.1836
Balt Solid Wood Round Tables                                        -1201.0581
BoxOffice By Design Rectangular and Half-Moon Meeting Room Tables   -1148.4375
Name: Profit, dtype: float64

### Task 6:
#### Find which Category has the highest total Sales

In [30]:
hts = df.groupby("Category")["Sales"].sum().nlargest(1)
hts

Category
Technology    836154.033
Name: Sales, dtype: float64

## Date-Based Analysis

### Task 1: Extract Year and Month
#### Question:
1. Create a new column named Order_Year containing the year from Order Date.
2. Create a new column named Order_Month containing the month number from Order Date.

In [34]:
df["Order_Year"] = df["Order Date"].dt.year

df["Order_Month"] = df["Order Date"].dt.month

df[["Order Date", "Order_Year", "Order_Month"]].head()

  Order Date  Order_Year  Order_Month
0 2016-11-08        2016           11
1 2016-11-08        2016           11
2 2016-06-12        2016            6
3 2015-10-11        2015           10
4 2015-10-11        2015           10

### Task 2: Calculate Yearly Sales
#### Question: Calculate the total Sales for each year.

In [35]:
yearly_sales = df.groupby("Order_Year")["Sales"].sum()
yearly_sales

Order_Year
2014    484247.4981
2015    470532.5090
2016    609205.5980
2017    733215.2552
Name: Sales, dtype: float64

### Task 3: Calculate Monthly Sales
####  Question: Calculate the total Sales for each month across all years. Display the results in month-number order, January to December.

In [41]:
monthly_sales = df.groupby("Order_Month")["Sales"].sum()

# monthly_sales = monthly_sales.sort_index()
monthly_sales

Order_Month
1      94924.8356
2      59751.2514
3     205005.4888
4     137762.1286
5     155028.8117
6     152718.6793
7     147238.0970
8     159044.0630
9     307649.9457
10    200322.9847
11    352461.0710
12    325293.5035
Name: Sales, dtype: float64

### Task 4: Calculate Monthly Sales by Year
#### Question: Calculate total Sales for each combination of year and month.

In [38]:
year_month_sales = df.groupby(
    ["Order_Year", "Order_Month"]
)["Sales"].sum()

year_month_sales

Order_Year  Order_Month
2014        1               14236.8950
            2                4519.8920
            3               55691.0090
            4               28295.3450
            5               23648.2870
            6               34595.1276
            7               33946.3930
            8               27909.4685
            9               81777.3508
            10              31453.3930
            11              78628.7167
            12              69545.6205
2015        1               18174.0756
            2               11951.4110
            3               38726.2520
            4               34195.2085
            5               30131.6865
            6               24797.2920
            7               28765.3250
            8               36898.3322
            9               64595.9180
            10              31404.9235
            11              75972.5635
            12              74919.5212
2016        1               18542.4910
            2               22978.8150
            3               51715.8750
            4               38750.0390
            5               56987.7280
            6               40344.5340
            7               39261.9630
            8               31115.3743
            9               73410.0249
            10              59687.7450
            11              79411.9658
            12              96999.0430
2017        1               43971.3740
            2               20301.1334
            3               58872.3528
            4               36521.5361
            5               44261.1102
            6               52981.7257
            7               45264.4160
            8               63120.8880
            9               87866.6520
            10              77776.9232
            11             118447.8250
            12              83829.3188
Name: Sales, dtype: float64

### Task 5: Find the Year with the Highest Total Profit
#### Question:
1. Calculate the total Profit for each year.
2. Identify the year with the highest total Profit.

In [42]:
yearly_profit = df.groupby("Order_Year")["Profit"].sum()

print("Yearly Profit:")
print(yearly_profit)

best_year = yearly_profit.idxmax()

highest_profit = yearly_profit.max()

print("Year with highest profit:", best_year)
print("Highest total profit:", highest_profit)

Yearly Profit:
Order_Year
2014    49543.9741
2015    61618.6037
2016    81795.1743
2017    93439.2696
Name: Profit, dtype: float64
Year with highest profit: 2017
Highest total profit: 93439.2696

### Task 6: Calculate Quarterly Sales
#### Question: Calculate total Sales for each quarter of the year.

In [43]:
df["Order_Quarter"] = df["Order Date"].dt.quarter

quarterly_sales = df.groupby("Order_Quarter")["Sales"].sum()
quarterly_sales

Order_Quarter
1    359681.5758
2    445509.6196
3    613932.1057
4    878077.5592
Name: Sales, dtype: float64

## Customer Analysis

### Task 1: Unique Customers
#### Find the total number of unique customers in the dataset.

In [47]:
df["Customer ID"].nunique()

793

### Task 2: Orders per Customer
#### Find the number of orders placed by each customer.

In [48]:
df.groupby(["Customer ID", "Customer Name"])["Order ID"].nunique()

Customer ID  Customer Name
AA-10315     Alex Avila             5
AA-10375     Allen Armold           9
AA-10480     Andrew Allen           4
AA-10645     Anna Andreadi          6
AB-10015     Aaron Bergman          3
                                   ..
XP-21865     Xylona Preis          11
YC-21895     Yoseph Carroll         5
YS-21880     Yana Sorensen          8
ZC-21910     Zuschuss Carroll      13
ZD-21925     Zuschuss Donatelli     5
Name: Order ID, Length: 793, dtype: int64

### Task 3: Find the Top 10 Customers by Sales
#### Question: Find the 10 customers with the highest total Sales.

In [51]:
df.groupby(["Customer ID", "Customer Name"])["Sales"].sum().sort_values(ascending=False).head(10)

Customer ID  Customer Name
SM-20320     Sean Miller           25043.050
TC-20980     Tamara Chand          19052.218
RB-19360     Raymond Buch          15117.339
TA-21385     Tom Ashbrook          14595.620
AB-10105     Adrian Barton         14473.571
KL-16645     Ken Lonsdale          14175.229
SC-20095     Sanjit Chand          14142.334
HL-15040     Hunter Lopez          12873.298
SE-20110     Sanjit Engle          12209.438
CC-12370     Christopher Conant    12129.072
Name: Sales, dtype: float64

### Task 4: Find the Top 10 Customers by Profit
#### Question: Find the 10 customers who generated the highest total Profit.

In [52]:
df.groupby(["Customer ID", "Customer Name"])["Profit"].sum().sort_values(ascending=False).head(10)

Customer ID  Customer Name
TC-20980     Tamara Chand            8981.3239
RB-19360     Raymond Buch            6976.0959
SC-20095     Sanjit Chand            5757.4119
HL-15040     Hunter Lopez            5622.4292
AB-10105     Adrian Barton           5444.8055
TA-21385     Tom Ashbrook            4703.7883
CM-12385     Christopher Martinez    3899.8904
KD-16495     Keith Dawkins           3038.6254
AR-10540     Andy Reiter             2884.6208
DR-12940     Daniel Raglin           2869.0760
Name: Profit, dtype: float64

### Task 5: Customer Segment Analysis
#### Question: Calculate total Sales and total Profit for each Segment.

In [54]:
df.groupby("Segment").agg(
    Total_Sales=("Sales", "sum"),
    Total_Profit=("Profit", "sum"))

              Total_Sales  Total_Profit
Segment
Consumer     1.161401e+06   134119.2092
Corporate    7.061464e+05    91979.1340
Home Office  4.296531e+05    60298.6785

### Task 6: Find the Customer with the Highest Number of Orders
#### Question: Identify the customer who placed the highest number of distinct orders.

In [55]:
orders_per_customer = (
    df.groupby(["Customer ID", "Customer Name"])["Order ID"]
    .nunique()
)

top_customer = orders_per_customer.idxmax()
highest_order_count = orders_per_customer.max()

print("Customer ID and Name:", top_customer)
print("Number of Orders:", highest_order_count)

Customer ID and Name: ('EP-13915', 'Emily Phan')
Number of Orders: 17

### Task 7: Calculate Average Sales per Customer
#### Question: Calculate the average total Sales generated per customer.

In [56]:
customer_sales = df.groupby("Customer ID")["Sales"].sum()

average_sales_per_customer = customer_sales.mean()

print("Average Sales per Customer:", average_sales_per_customer)

Average Sales per Customer: 2896.848499747793

### Task 8: Analyze Customer Purchase Frequency
#### Question: Count how many customers placed:
- Only 1 order
- Between 2 and 5 orders
- More than 5 orders

In [57]:
orders_per_customer = df.groupby("Customer ID")["Order ID"].nunique()

one_order = (orders_per_customer == 1).sum()

two_to_five_orders = (
    (orders_per_customer >= 2) &
    (orders_per_customer <= 5)
).sum()

more_than_five_orders = (orders_per_customer > 5).sum()

print("Customers with 1 order:", one_order)
print("Customers with 2–5 orders:", two_to_five_orders)
print("Customers with more than 5 orders:", more_than_five_orders)

Customers with 1 order: 12
Customers with 2–5 orders: 317
Customers with more than 5 orders: 464

## Business Insights & Final Report

### Task 1: Overall Business Performance
#### Question: Calculate Total Sales, Total Profit, Total Orders, Total Unique Customers, and Overall Profit Margin.

In [58]:
total_sales = df["Sales"].sum()
total_profit = df["Profit"].sum()
total_orders = df["Order ID"].nunique()
total_customers = df["Customer ID"].nunique()

profit_margin = (total_profit / total_sales) * 100

print("Total Sales:", total_sales)
print("Total Profit:", total_profit)
print("Total Orders:", total_orders)
print("Total Unique Customers:", total_customers)
print("Overall Profit Margin:", round(profit_margin, 2), "%")

Total Sales: 2297200.8603
Total Profit: 286397.0217
Total Orders: 5009
Total Unique Customers: 793
Overall Profit Margin: 12.47 %

### Task 2: Best and Worst Performing Category
#### Question: Identify the category with the highest Sales, highest Profit, and lowest Profit.

In [59]:
category_analysis = df.groupby("Category").agg(
    Total_Sales=("Sales", "sum"),
    Total_Profit=("Profit", "sum")
)

print(category_analysis)

best_sales_category = category_analysis["Total_Sales"].idxmax()
best_profit_category = category_analysis["Total_Profit"].idxmax()
worst_profit_category = category_analysis["Total_Profit"].idxmin()

print("Highest Sales Category:", best_sales_category)
print("Highest Profit Category:", best_profit_category)
print("Lowest Profit Category:", worst_profit_category)

                 Total_Sales  Total_Profit
Category
Furniture        741999.7953    18451.2728
Office Supplies  719047.0320   122490.8008
Technology       836154.0330   145454.9481
Highest Sales Category: Technology
Highest Profit Category: Technology
Lowest Profit Category: Furniture

### Task 3: Regional Performance
#### Question: Calculate total Sales, total Profit, and Profit Margin for each Region. Identify the regions with the highest Sales and Profit.

In [60]:
region_analysis = df.groupby("Region").agg(
    Total_Sales=("Sales", "sum"),
    Total_Profit=("Profit", "sum")
)

region_analysis["Profit_Margin"] = (
    region_analysis["Total_Profit"] /
    region_analysis["Total_Sales"]
) * 100

print(region_analysis.round(2))

highest_sales_region = region_analysis["Total_Sales"].idxmax()
highest_profit_region = region_analysis["Total_Profit"].idxmax()

print("Highest Sales Region:", highest_sales_region)
print("Highest Profit Region:", highest_profit_region)

         Total_Sales  Total_Profit  Profit_Margin
Region
Central    501239.89      39706.36           7.92
East       678781.24      91522.78          13.48
South      391721.90      46749.43          11.93
West       725457.82     108418.45          14.94
Highest Sales Region: West
Highest Profit Region: West

### Task 4: Top 10 Loss-Making Products
#### Question: Find the 10 products with the lowest total Profit. Display Product Name, Total Sales, and Total Profit.

In [61]:
product_analysis = df.groupby("Product Name").agg(
    Total_Sales=("Sales", "sum"),
    Total_Profit=("Profit", "sum")
)

loss_making_products = product_analysis.sort_values(
    by="Total_Profit",
    ascending=True
).head(10)

print(loss_making_products)

                                                    Total_Sales  Total_Profit
Product Name
Cubify CubeX 3D Printer Double Head Print             11099.963    -8879.9704
Lexmark MX611dhe Monochrome Laser Printer             16829.901    -4589.9730
Cubify CubeX 3D Printer Triple Head Print              7999.980    -3839.9904
Chromcraft Bull-Nose Wood Oval Conference Table...     9917.640    -2876.1156
Bush Advantage Collection Racetrack Conference ...     9544.725    -1934.3976
GBC DocuBind P400 Electric Binding System             17965.068    -1878.1662
Cisco TelePresence System EX90 Videoconferencin...    22638.480    -1811.0784
Martin Yale Chadless Opener Electric Letter Opener    16656.200    -1299.1836
Balt Solid Wood Round Tables                           6518.754    -1201.0581
BoxOffice By Design Rectangular and Half-Moon M...     1706.250    -1148.4375

### Task 5: Monthly Sales Trend
#### Question: Calculate total Sales for each month across all years. Identify the months with the highest and lowest Sales.

In [64]:
import numpy as np
df["Order Date"] = pd.to_datetime(df["Order Date"])

df["Order_Month"] = df["Order Date"].dt.month

monthly_sales = df.groupby("Order_Month")["Sales"].sum()
monthly_sales = monthly_sales.sort_index()

print("Monthly Sales:")
print(monthly_sales)

highest_sales_month = monthly_sales.idxmax()
lowest_sales_month = monthly_sales.idxmin()

print("Month with Highest Sales:", highest_sales_month)
print("Month with Lowest Sales:", lowest_sales_month)

Monthly Sales:
Order_Month
1      94924.8356
2      59751.2514
3     205005.4888
4     137762.1286
5     155028.8117
6     152718.6793
7     147238.0970
8     159044.0630
9     307649.9457
10    200322.9847
11    352461.0710
12    325293.5035
Name: Sales, dtype: float64
Month with Highest Sales: 11
Month with Lowest Sales: 2

### Task 6: Discount vs Profit Analysis
#### Question: Divide orders into No Discount, Low Discount, and High Discount groups. Calculate Total Sales, Total Profit, and Average Profit for each group.

In [66]:
conditions = [
    df["Discount"] == 0,
    (df["Discount"] > 0) & (df["Discount"] <= 0.2),
    df["Discount"] > 0.2
]

labels = [
    "No Discount",
    "Low Discount",
    "High Discount"
]

df["Discount_Group"] = np.select(
    conditions,
    labels,
    default="Other"
)

discount_analysis = df.groupby("Discount_Group").agg(
    Total_Sales=("Sales", "sum"),
    Total_Profit=("Profit", "sum"),
    Average_Profit=("Profit", "mean")
)

print(discount_analysis.round(2))

                Total_Sales  Total_Profit  Average_Profit
Discount_Group
High Discount     362770.15    -135376.06          -97.18
Low Discount      846522.24     100785.47           26.50
No Discount      1087908.47     320987.60           66.90

### Task 8: Final Business Insights & Recommendations

In [67]:
print("1. Overall Performance")
print("Total Sales:", round(total_sales, 2))
print("Total Profit:", round(total_profit, 2))
print("Profit Margin:", round(profit_margin, 2), "%")

print("\n2. Category Performance")
print(category_analysis.sort_values(
    by="Total_Profit",
    ascending=False
))

print("\n3. Regional Performance")
print(region_analysis.round(2))

print("\n4. Loss-Making Products")
print(loss_making_products)

print("\n5. Monthly Sales")
print(monthly_sales)

1. Overall Performance
Total Sales: 2297200.86
Total Profit: 286397.02
Profit Margin: 12.47 %

2. Category Performance
                 Total_Sales  Total_Profit
Category
Technology       836154.0330   145454.9481
Office Supplies  719047.0320   122490.8008
Furniture        741999.7953    18451.2728

3. Regional Performance
         Total_Sales  Total_Profit  Profit_Margin
Region
Central    501239.89      39706.36           7.92
East       678781.24      91522.78          13.48
South      391721.90      46749.43          11.93
West       725457.82     108418.45          14.94

4. Loss-Making Products
                                                    Total_Sales  Total_Profit
Product Name
Cubify CubeX 3D Printer Double Head Print             11099.963    -8879.9704
Lexmark MX611dhe Monochrome Laser Printer             16829.901    -4589.9730
Cubify CubeX 3D Printer Triple Head Print              7999.980    -3839.9904
Chromcraft Bull-Nose Wood Oval Conference Table...     9917.640    -2876.1156
Bush Advantage Collection Racetrack Conference ...     9544.725    -1934.3976
GBC DocuBind P400 Electric Binding System             17965.068    -1878.1662
Cisco TelePresence System EX90 Videoconferencin...    22638.480    -1811.0784
Martin Yale Chadless Opener Electric Letter Opener    16656.200    -1299.1836
Balt Solid Wood Round Tables                           6518.754    -1201.0581
BoxOffice By Design Rectangular and Half-Moon M...     1706.250    -1148.4375

5. Monthly Sales
Order_Month
1      94924.8356
2      59751.2514
3     205005.4888
4     137762.1286
5     155028.8117
6     152718.6793
7     147238.0970
8     159044.0630
9     307649.9457
10    200322.9847
11    352461.0710
12    325293.5035
Name: Sales, dtype: float64

#   ====================== END ====================