# Every Thing About Panda and Project

In [1]:
import pandas as pd
pd.__version__

'2.3.3'

In [2]:
data = [10,20,30,40,50]
df= pd.Series(data)

In [3]:
df

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [4]:
data = {
    "Name":["Vipul","Ram","Musu","Lalu"],
    "Age":[20,25,22,25]
}
df = pd.DataFrame(data)

In [5]:
df

    Name  Age
0  Vipul   20
1    Ram   25
2   Musu   22
3   Lalu   25

In [5]:
data = {
    "Name":["Vipul","Musu","Annu","Ram"],
    "Age":[20,30,22,20],
    "Marks":[40,45,35,30]
}
df = pd.DataFrame(data)
df.shape
df
df.info()
df.describe
df.columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Age     4 non-null      int64
 2   Marks   4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes

Index(['Name', 'Age', 'Marks'], dtype='object')

In [6]:
df.describe()

             Age      Marks
count   4.000000   4.000000
mean   23.000000  37.500000
std     4.760952   6.454972
min    20.000000  30.000000
25%    20.000000  33.750000
50%    21.000000  37.500000
75%    24.000000  41.250000
max    30.000000  45.000000

In [16]:
# df.describe
# df.shape
len(df.columns)

3

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Age     4 non-null      int64
 2   Marks   4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes

In [8]:
df["Name"]

0    Vipul
1     Musu
2     Annu
3      Ram
Name: Name, dtype: object

In [9]:
df[["Name","Age"]]

    Name  Age
0  Vipul   20
1   Musu   30
2   Annu   22
3    Ram   20

In [10]:
df.iloc[0]

Name     Vipul
Age         20
Marks       40
Name: 0, dtype: object

#### 3. Rows select karna — loc aur iloc
#### Dono bahut important hain, bhai.
#### Method	Kaise select karta hai?
#### df.iloc[0]	Position ke basis par pehli row
#### df.iloc[1:4]	Position 1, 2, 3 wali rows
#### df.loc[0]	Index label 0 wali row
#### df.loc[0:2]	Index labels 0, 1, 2 wali rows; end included

In [11]:
df.loc[0]

Name     Vipul
Age         20
Marks       40
Name: 0, dtype: object

In [12]:
df.iloc[0]

Name     Vipul
Age         20
Marks       40
Name: 0, dtype: object

In [18]:
df.loc[1,"Name"]

'Musu'

In [15]:
df.iloc[1,:1]

Name    Musu
Name: 1, dtype: object

In [13]:
data = {
    "Name": ["Vipul", "Ram", "Musu", "Lalu", "Riya"],
    "Age": [20, 25, 22, 25, 19],
    "Marks": [85, 70, 92, 65, 95],
    "City": ["Delhi", "Mumbai", "Delhi", "Pune", "Mumbai"]
}

df = pd.DataFrame(data)

df

    Name  Age  Marks    City
0  Vipul   20     85   Delhi
1    Ram   25     70  Mumbai
2   Musu   22     92   Delhi
3   Lalu   25     65    Pune
4   Riya   19     95  Mumbai

In [15]:
# df.shape
df[df["Marks"] > 80]

    Name  Age  Marks    City
0  Vipul   20     85   Delhi
2   Musu   22     92   Delhi
4   Riya   19     95  Mumbai

In [19]:
df[df["Marks"] > 80]

    Name  Age  Marks    City
0  Vipul   20     85   Delhi
2   Musu   22     92   Delhi
4   Riya   19     95  Mumbai

In [22]:
df[df["Age"] >= 22]

   Name  Age  Marks    City
1   Ram   25     70  Mumbai
2  Musu   22     92   Delhi
3  Lalu   25     65    Pune

In [16]:
df[df["Marks"].between(70,90)]

    Name  Age  Marks    City
0  Vipul   20     85   Delhi
1    Ram   25     70  Mumbai

In [26]:
# Marks 80 se zyada AND age 22 se kam
df[(df["Marks"] > 80) & (df["Age"] < 22)]

    Name  Age  Marks    City
0  Vipul   20     85   Delhi
4   Riya   19     95  Mumbai

In [27]:
# Delhi OR Mumbai
df[(df["City"] == "Delhi") | (df["City"] == "Mumbai")]

    Name  Age  Marks    City
0  Vipul   20     85   Delhi
1    Ram   25     70  Mumbai
2   Musu   22     92   Delhi
4   Riya   19     95  Mumbai

In [17]:
df[["Name","City"]]

    Name    City
0  Vipul   Delhi
1    Ram  Mumbai
2   Musu   Delhi
3   Lalu    Pune
4   Riya  Mumbai

In [31]:
df[(df["Age"] >= 22 ) & (df["Marks"] > 70)]

   Name  Age  Marks   City
2  Musu   22     92  Delhi

In [33]:
df.sort_values("Age")

    Name  Age  Marks    City
4   Riya   19     95  Mumbai
0  Vipul   20     85   Delhi
2   Musu   22     92   Delhi
1    Ram   25     70  Mumbai
3   Lalu   25     65    Pune

#### Marks In Desending Order

In [19]:
df.sort_values("Marks",ascending=False)

    Name  Age  Marks    City
4   Riya   19     95  Mumbai
2   Musu   22     92   Delhi
0  Vipul   20     85   Delhi
1    Ram   25     70  Mumbai
3   Lalu   25     65    Pune

In [21]:
data = {
    "Name": ["Vipul", "Ram", "Musu", "Lalu", "Riya"],
    "Age": [20, None, 22, 25, None],
    "Marks": [85, 70, None, 65, 95]
}

df = pd.DataFrame(data)

In [22]:
df.isnull()

    Name    Age  Marks
0  False  False  False
1  False   True  False
2  False  False   True
3  False  False  False
4  False   True  False

In [42]:
# Har column mein missing values kitni hain
df.isnull().sum()

Name     0
Age      2
Marks    1
dtype: int64

In [43]:
# Missing values wali rows
df[df.isnull().any(axis=1)]

   Name   Age  Marks
1   Ram   NaN   70.0
2  Musu  22.0    NaN
4  Riya   NaN   95.0

### Handling the Missing Values

In [45]:
# Missing values wali rows remove karna
df.dropna()

    Name   Age  Marks
0  Vipul  20.0   85.0
3   Lalu  25.0   65.0

In [23]:
# Missing Age ko average age se fill karna
df["Age"] = df["Age"].fillna(df["Age"].mean())

In [24]:
df

    Name        Age  Marks
0  Vipul  20.000000   85.0
1    Ram  22.333333   70.0
2   Musu  22.000000    NaN
3   Lalu  25.000000   65.0
4   Riya  22.333333   95.0

In [26]:
df["Marks"] = df["Marks"].fillna(df["Marks"].mean())

In [27]:
df

    Name        Age  Marks
0  Vipul  20.000000  85.00
1    Ram  22.333333  70.00
2   Musu  22.000000  78.75
3   Lalu  25.000000  65.00
4   Riya  22.333333  95.00

### Part C — Duplicates

In [54]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [56]:
df.duplicated().sum()

np.int64(0)

In [57]:
# Duplicate rows remove karna
df.drop_duplicates()

    Name        Age  Marks
0  Vipul  20.000000  85.00
1    Ram  22.333333  70.00
2   Musu  22.000000  78.75
3   Lalu  25.000000  65.00
4   Riya  22.333333  95.00

In [58]:
df.duplicated(subset=["Name"])

0    False
1    False
2    False
3    False
4    False
dtype: bool

### Data Modification

#### Adding New Columns

In [28]:
data = {
    "Name": ["Vipul", "Ram", "Musu", "Lalu"],
    "Age": [20, 25, 22, 25],
    "Marks": [85, 70, 92, 65]
}

df = pd.DataFrame(data)

df["City"] = ["Prayagraj", "Delhi", "Lucknow", "Kanpur"]

In [60]:
df

    Name  Age  Marks       City
0  Vipul   20     85  Prayagraj
1    Ram   25     70      Delhi
2   Musu   22     92    Lucknow
3   Lalu   25     65     Kanpur

In [29]:
df["Marks"] = df["Marks"] + 5

In [30]:
df

    Name  Age  Marks       City
0  Vipul   20     90  Prayagraj
1    Ram   25     75      Delhi
2   Musu   22     97    Lucknow
3   Lalu   25     70     Kanpur

In [32]:
df.loc[df["Marks"] >= 90, "Result"] = "Excellent"

In [33]:
df.loc[df["Marks"] < 90, "Result"] = "Average"

In [34]:
df

    Name  Age  Marks       City     Result
0  Vipul   20     90  Prayagraj  Excellent
1    Ram   25     75      Delhi    Average
2   Musu   22     97    Lucknow  Excellent
3   Lalu   25     70     Kanpur    Average

In [36]:
df = df.rename(columns={"Result":"Performance"})

In [37]:
df

    Name  Age  Marks       City Performance
0  Vipul   20     90  Prayagraj   Excellent
1    Ram   25     75      Delhi     Average
2   Musu   22     97    Lucknow   Excellent
3   Lalu   25     70     Kanpur     Average

In [73]:
df.drop(columns={"City"})

    Name  Age  Marks Performance
0  Vipul   20     90   Excellent
1    Ram   25     75     Average
2   Musu   22     97   Excellent
3   Lalu   25     70     Average

In [74]:
df.drop(index=0)

   Name  Age  Marks     City Performance
1   Ram   25     75    Delhi     Average
2  Musu   22     97  Lucknow   Excellent
3  Lalu   25     70   Kanpur     Average

In [39]:
df["Passed"]=True

In [40]:
df

    Name  Age  Marks       City Performance  Passed
0  Vipul   20     90  Prayagraj   Excellent    True
1    Ram   25     75      Delhi     Average    True
2   Musu   22     97    Lucknow   Excellent    True
3   Lalu   25     70     Kanpur     Average    True

#### GroupBy & Aggregation

In [41]:
data = {
    "Name": ["Vipul", "Ram", "Musu", "Lalu", "Riya", "Aman"],
    "City": ["Delhi", "Mumbai", "Delhi", "Mumbai", "Delhi", "Mumbai"],
    "Marks": [85, 70, 92, 65, 95, 78],
    "Age": [20, 25, 22, 25, 19, 21]
}

df = pd.DataFrame(data)

In [78]:
df.groupby("City")["Marks"].mean()

City
Delhi     90.666667
Mumbai    71.000000
Name: Marks, dtype: float64

In [79]:
df.groupby("City")["Name"].count()

City
Delhi     3
Mumbai    3
Name: Name, dtype: int64

In [42]:
df.groupby("City")["Marks"].max()

City
Delhi     95
Mumbai    78
Name: Marks, dtype: int64

In [43]:
df.groupby("City")["Marks"].agg(
    ["mean", "max", "min", "count"]
)

             mean  max  min  count
City
Delhi   90.666667   95   85      3
Mumbai  71.000000   78   65      3

In [82]:
df["City"].value_counts()

City
Delhi     3
Mumbai    3
Name: count, dtype: int64

In [44]:
df1 = pd.DataFrame({
    "ID": [1, 2, 3],
    "Name": ["Vipul", "Ram", "Musu"]
})

df2 = pd.DataFrame({
    "ID": [1, 2, 3],
    "Marks": [85, 70, 92]
})

print(df1)
print(df2)

   ID   Name
0   1  Vipul
1   2    Ram
2   3   Musu
   ID  Marks
0   1     85
1   2     70
2   3     92

In [84]:
result = pd.merge(df1, df2, on="ID")
print(result)

   ID   Name  Marks
0   1  Vipul     85
1   2    Ram     70
2   3   Musu     92

In [ ]:
pd.merge(df1, df2, on="ID", how="inner")
pd.merge(df1, df2, on="ID", how="left")
pd.merge(df1, df2, on="ID", how="right")
pd.merge(df1, df2, on="ID", how="outer")

In [85]:
batch1 = pd.DataFrame({
    "Name": ["Vipul", "Ram"],
    "Marks": [85, 70]
})

batch2 = pd.DataFrame({
    "Name": ["Musu", "Lalu"],
    "Marks": [92, 65]
})

result = pd.concat([batch1, batch2], ignore_index=True)

print(result)

    Name  Marks
0  Vipul     85
1    Ram     70
2   Musu     92
3   Lalu     65

In [86]:
df1 = pd.DataFrame({
    "Name": ["Vipul", "Ram", "Musu"]
}, index=[1, 2, 3])

df2 = pd.DataFrame({
    "Marks": [85, 70, 92]
}, index=[1, 2, 3])

result = df1.join(df2)
print(result)

    Name  Marks
1  Vipul     85
2    Ram     70
3   Musu     92

In [88]:
df.dtypes

Name     object
City     object
Marks     int64
Age       int64
dtype: object

In [89]:
df["Marks"] = df["Marks"].astype(int)

In [90]:
df["Name"] = df["Name"].str.strip()

In [91]:
df["Name"] = df["Name"].str.lower()

In [92]:
data = {
    "Name": ["  VIPUL ", " RAM", "Musu  ", "LALU"],
    "Marks": ["85", "70", "92", "65"]
}

df = pd.DataFrame(data)

In [93]:
data = {
    "Name": ["Vipul", "Ram", "Musu", "Lalu", "Riya"],
    "City": ["Delhi", "Mumbai", "Delhi", "Pune", "Mumbai"],
    "Marks": [85, 70, 92, 65, 95],
    "Result": ["Pass", "Fail", "Pass", "Fail", "Pass"]
}

df = pd.DataFrame(data)

In [ ]:
df = pd.read_csv("students.csv")

In [ ]:
df = pd.read_excel("students.xlsx")

In [ ]:
df.to_csv("cleaned_students.csv", index=False)

In [94]:
import pandas as pd

data = {
    "Name": ["Vipul", "Ram", "Musu", "Riya"],
    "Appointment": ["2026-10-11", "2026-10-12", "2026-10-15", "2026-10-20"]
}

df = pd.DataFrame(data)

In [95]:
df["Appointment"] = pd.to_datetime(df["Appointment"])

In [96]:
df["Year"] = df["Appointment"].dt.year
df["Month"] = df["Appointment"].dt.month
df["Day"] = df["Appointment"].dt.day

In [97]:
df[df["Appointment"] >= "2026-10-15"]

   Name Appointment  Year  Month  Day
2  Musu  2026-10-15  2026     10   15
3  Riya  2026-10-20  2026     10   20

# Practice Project

In [99]:
import pandas as pd

data = {
    "Name": [" Vipul ", "Ram", "Musu", "Vipul ", "Riya", "Aman"],
    "City": ["Delhi", "Mumbai", "Delhi", "Delhi", None, "Mumbai"],
    "Marks": [85, 70, None, 85, 95, 40],
    "Age": [20, 21, 22, 20, None, 23]
}

df = pd.DataFrame(data)

print(df)

      Name    City  Marks   Age
0   Vipul    Delhi   85.0  20.0
1      Ram  Mumbai   70.0  21.0
2     Musu   Delhi    NaN  22.0
3   Vipul    Delhi   85.0  20.0
4     Riya    None   95.0   NaN
5     Aman  Mumbai   40.0  23.0

In [45]:
import pandas as pd

data = {
    "Name": [" Vipul ", "Ram", "Musu", "Vipul ", "Riya", "Aman"],
    "City": ["Delhi", "Mumbai", "Delhi", "Delhi", None, "Mumbai"],
    "Marks": [85, 70, None, 85, 95, 40],
    "Age": [20, 21, 22, 20, None, 23]
}

df = pd.DataFrame(data)

print(df)

      Name    City  Marks   Age
0   Vipul    Delhi   85.0  20.0
1      Ram  Mumbai   70.0  21.0
2     Musu   Delhi    NaN  22.0
3   Vipul    Delhi   85.0  20.0
4     Riya    None   95.0   NaN
5     Aman  Mumbai   40.0  23.0

In [46]:
df.duplicated().sum()

np.int64(0)

In [47]:
df.duplicated().sum()

np.int64(0)

In [48]:
df = df.drop_duplicates()

In [ ]:
# Aage-peeche ke spaces hatao
df['Name'] = df['Name'].str.strip()

In [49]:
df["City"]=df["City"].fillna("Unknown")

In [50]:
df

      Name     City  Marks   Age
0   Vipul     Delhi   85.0  20.0
1      Ram   Mumbai   70.0  21.0
2     Musu    Delhi    NaN  22.0
3   Vipul     Delhi   85.0  20.0
4     Riya  Unknown   95.0   NaN
5     Aman   Mumbai   40.0  23.0

In [51]:
df["Marks"] = df["Marks"].fillna(df["Marks"].mean())

In [53]:
df.sort_values("Marks",ascending=False)

      Name     City  Marks   Age
4     Riya  Unknown   95.0   NaN
0   Vipul     Delhi   85.0  20.0
3   Vipul     Delhi   85.0  20.0
2     Musu    Delhi   75.0  22.0
1      Ram   Mumbai   70.0  21.0
5     Aman   Mumbai   40.0  23.0

In [54]:
df['Name'] = df['Name'].str.lower()

In [55]:
df

      Name     City  Marks   Age
0   vipul     Delhi   85.0  20.0
1      ram   Mumbai   70.0  21.0
2     musu    Delhi   75.0  22.0
3   vipul     Delhi   85.0  20.0
4     riya  Unknown   95.0   NaN
5     aman   Mumbai   40.0  23.0

In [56]:
# highest marks
df["Marks"].max()

95.0

In [57]:
sort_data = df.sort_values("Marks",ascending=False)
sort_data.head(3)

      Name     City  Marks   Age
4     riya  Unknown   95.0   NaN
0   vipul     Delhi   85.0  20.0
3   vipul     Delhi   85.0  20.0

In [58]:
df.groupby("City")["Marks"].max()

City
Delhi      85.0
Mumbai     70.0
Unknown    95.0
Name: Marks, dtype: float64